spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/children_camp
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect:
        show_sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

jwt:
  secret:
    access: SecretAccess
    refresh: RefreshAccess